/** Offline, human-readable clue words. Keep spelling stable: history uses words as IDs. */
const words = (text: string) => text.split('|').map(w => w.trim()).filter(Boolean);

export const IMPOSTER_BANKS: Record<string, string[]> = {
  animals: words(`Dog|Cat|Elephant|Lion|Tiger|Penguin|Giraffe|Dolphin|Eagle|Shark|Rabbit|Horse|Bear|Wolf|Fox|Otter|Beaver|Badger|Hedgehog|Squirrel|Raccoon|Skunk|Moose|Deer|Antelope|Gazelle|Bison|Buffalo|Camel|Llama|Alpaca|Kangaroo|Koala|Wombat|Platypus|Sloth|Armadillo|Anteater|Panda|Gorilla|Chimpanzee|Orangutan|Lemur|Baboon|Meerkat|Hyena|Leopard|Cheetah|Lynx|Jaguar|Hippopotamus|Rhinoceros|Zebra|Donkey|Goat|Sheep|Cow|Pig|Chicken|Turkey|Duck|Goose|Swan|Peacock|Flamingo|Pelican|Puffin|Ostrich|Emu|Owl|Hawk|Falcon|Parrot|Toucan|Hummingbird|Woodpecker|Kingfisher|Crow|Raven|Magpie|Sparrow|Pigeon|Robin|Seagull|Albatross|Seal|Walrus|Whale|Orca|Manatee|Octopus|Squid|Jellyfish|Seahorse|Starfish|Crab|Lobster|Shrimp|Clam|Oyster|Turtle|Tortoise|Crocodile|Alligator|Iguana|Chameleon|Gecko|Snake|Frog|Toad|Salamander|Axolotl|Bat|Mouse|Rat|Hamster|Guinea Pig|Ferret|Mole|Porcupine|Butterfly|Moth|Dragonfly|Ladybug|Grasshopper|Cricket|Ant|Bee|Beetle|Snail|Slug|Earthworm|Scorpion|Spider|Mantis|Firefly|Centipede|Praying Mantis|Swordfish|Stingray`),
  food: words(`Pizza|Sushi|Burger|Pasta|Taco|Chocolate|Ice Cream|Pancake|Steak|Salad|Soup|Sandwich|Cake|Cookie|Bread|Waffle|Croissant|Bagel|Pretzel|Muffin|Brownie|Cupcake|Doughnut|Cheesecake|Tiramisu|Baklava|Pudding|Custard|Jelly|Marshmallow|Popcorn|Granola|Oatmeal|Cereal|Yogurt|Cheese|Butter|Cream|Honey|Jam|Marmalade|Peanut Butter|Hummus|Guacamole|Salsa|Pesto|Ketchup|Mustard|Mayonnaise|Soy Sauce|Olive Oil|Vinegar|Salt|Pepper|Cinnamon|Ginger|Garlic|Basil|Mint|Parsley|Rice|Noodles|Couscous|Quinoa|Risotto|Lasagna|Ravioli|Gnocchi|Ramen|Dumpling|Spring Roll|Falafel|Kebab|Burrito|Nachos|Quesadilla|Omelet|Scrambled Eggs|French Toast|Baked Potato|French Fries|Mashed Potato|Onion Rings|Cornbread|Focaccia|Sourdough|Pita|Baguette|Scone|Biscuit|Apple Pie|Pumpkin Pie|Lemon Tart|Fruit Salad|Smoothie|Milkshake|Lemonade|Orange Juice|Hot Chocolate|Coffee|Tea|Coconut Water|Apple|Pear|Banana|Peach|Plum|Apricot|Cherry|Strawberry|Blueberry|Raspberry|Grape|Mango|Pineapple|Papaya|Kiwi|Watermelon|Cantaloupe|Pomegranate|Fig|Date|Lemon|Lime|Orange|Grapefruit|Coconut|Avocado|Tomato|Cucumber|Carrot|Broccoli|Cauliflower|Spinach|Lettuce|Cabbage|Eggplant|Zucchini|Pumpkin|Mushroom|Asparagus|Celery|Radish|Beetroot|Sweet Potato|Chickpea|Lentil|Pea|Pistachio|Almond|Walnut|Cashew|Hazelnut|Sesame|Sunflower Seed`),
  places: words(`Hospital|Library|School|Restaurant|Bank|Airport|Museum|Beach|Stadium|Cinema|Park|Church|Mall|Gym|Zoo|Aquarium|Planetarium|Observatory|Theater|Opera House|Concert Hall|Art Gallery|Bookshop|Bakery|Cafe|Post Office|Police Station|Fire Station|Train Station|Bus Station|Harbor|Marina|Lighthouse|Castle|Palace|Fortress|Temple|Mosque|Cathedral|Monastery|Town Hall|Courthouse|University|Kindergarten|Playground|Skate Park|Swimming Pool|Ice Rink|Bowling Alley|Arcade|Fairground|Circus|Theme Park|Water Park|Botanical Garden|Greenhouse|Orchard|Vineyard|Farm|Barn|Stable|Windmill|Watermill|Factory|Workshop|Warehouse|Garage|Petrol Station|Car Wash|Supermarket|Market|Flea Market|Flower Shop|Toy Shop|Pharmacy|Barbershop|Salon|Tailor Shop|Jewelry Shop|Shoe Shop|Hotel|Hostel|Campsite|Treehouse|Cabin|Cottage|Houseboat|Apartment|Penthouse|Balcony|Attic|Basement|Kitchen|Pantry|Living Room|Dining Room|Bedroom|Bathroom|Laundry Room|Hallway|Staircase|Rooftop|Courtyard|Garden|Patio|Driveway|Tunnel|Bridge|Roundabout|Crossroads|Footpath|Pier|Boardwalk|Lookout|Cave|Quarry|Mine|Dam|Reservoir|Fountain|Square|Picnic Area|Visitor Center|Animal Shelter|Recycling Center|Community Center|Recording Studio|Dance Studio|Pottery Studio|Science Lab|Weather Station`),
  jobs: words(`Doctor|Teacher|Chef|Pilot|Firefighter|Astronaut|Detective|Farmer|Architect|Nurse|Dentist|Lawyer|Artist|Singer|Actor|Baker|Butcher|Fishmonger|Barista|Waiter|Hotel Receptionist|Tour Guide|Travel Agent|Librarian|Bookseller|Journalist|Editor|Author|Poet|Translator|Interpreter|Photographer|Camera Operator|Film Director|Animator|Illustrator|Graphic Designer|Fashion Designer|Tailor|Shoemaker|Jeweler|Watchmaker|Carpenter|Plumber|Electrician|Mechanic|Welder|Builder|Roofer|Painter|Gardener|Florist|Beekeeper|Shepherd|Fisherman|Veterinarian|Zookeeper|Dog Trainer|Marine Biologist|Botanist|Geologist|Meteorologist|Archaeologist|Historian|Astronomer|Chemist|Physicist|Engineer|Programmer|Game Designer|Accountant|Bank Teller|Shopkeeper|Cashier|Courier|Postal Worker|Bus Driver|Taxi Driver|Train Driver|Ship Captain|Sailor|Flight Attendant|Air Traffic Controller|Lifeguard|Paramedic|Surgeon|Physiotherapist|Pharmacist|Optician|Coach|Referee|Dancer|Choreographer|Musician|Composer|Conductor|Piano Tuner|Sound Engineer|Magician|Clown|Puppeteer|Sculptor|Potter|Weaver|Glassblower|Furniture Restorer|Museum Curator|Park Ranger|Ski Instructor|Diving Instructor|Fitness Trainer|Yoga Instructor|Event Planner|Wedding Planner|Auctioneer|News Presenter|Radio Host|Sports Commentator|Crossing Guard|Locksmith|Chimney Sweep|Window Cleaner|Waste Collector|Cartographer|Surveyor`),
  movies: words(`Titanic|Jaws|Avatar|Frozen|Batman|Shrek|Inception|Gladiator|Rocky|Aladdin|Jumanji|Moana|Coco|Bolt|Cars|Toy Story|Finding Nemo|Finding Dory|The Lion King|The Little Mermaid|Beauty and the Beast|Cinderella|Snow White|Sleeping Beauty|Pinocchio|Dumbo|Bambi|Peter Pan|The Jungle Book|Mulan|Pocahontas|Hercules|Tarzan|Tangled|Encanto|Zootopia|Ratatouille|WALL-E|Up|Inside Out|Soul|Luca|Brave|The Incredibles|Monsters Inc.|Kung Fu Panda|Madagascar|Ice Age|Rio|Happy Feet|Chicken Run|Paddington|The Lego Movie|Despicable Me|Minions|How to Train Your Dragon|The Iron Giant|Spirited Away|My Neighbor Totoro|Kiki's Delivery Service|The Wizard of Oz|Mary Poppins|The Sound of Music|Willy Wonka and the Chocolate Factory|Home Alone|Back to the Future|Ghostbusters|Jurassic Park|E.T.|Star Wars|Harry Potter|The Lord of the Rings|The Hobbit|Pirates of the Caribbean|Indiana Jones|The Matrix|Spider-Man|Superman|Wonder Woman|Black Panther|Iron Man|The Avengers|Ant-Man|Doctor Strange|The Karate Kid|Mrs. Doubtfire|Night at the Museum|The Mask|The Truman Show|Groundhog Day|Casablanca|King Kong|Godzilla|Grease|La La Land|Singin' in the Rain|The Princess Bride|The NeverEnding Story|The Secret Garden|The Polar Express`),
  objects: words(`Umbrella|Telescope|Diamond|Compass|Candle|Clock|Mirror|Lantern|Flashlight|Binoculars|Microscope|Magnifying Glass|Camera|Tripod|Projector|Radio|Television|Remote Control|Headphones|Speaker|Microphone|Laptop|Keyboard|Mouse Pad|Printer|Calculator|Telephone|Smartwatch|Charger|Battery|Light Bulb|Fan|Heater|Air Conditioner|Vacuum Cleaner|Washing Machine|Dishwasher|Refrigerator|Freezer|Oven|Microwave|Toaster|Blender|Kettle|Coffee Maker|Teapot|Saucepan|Frying Pan|Colander|Whisk|Spatula|Rolling Pin|Cutting Board|Grater|Peeler|Corkscrew|Bottle Opener|Thermos|Lunchbox|Water Bottle|Mug|Plate|Bowl|Fork|Spoon|Chopsticks|Napkin|Tablecloth|Apron|Oven Mitt|Broom|Dustpan|Mop|Bucket|Sponge|Brush|Comb|Toothbrush|Toothpaste|Soap|Towel|Hairdryer|Scissors|Stapler|Paper Clip|Rubber Band|Envelope|Stamp|Notebook|Bookmark|Pencil|Eraser|Ruler|Protractor|Paintbrush|Crayon|Chalk|Glue Stick|Tape|Needle|Thread|Thimble|Safety Pin|Button|Zipper|Padlock|Key|Doorbell|Hinge|Doorknob|Ladder|Hammer|Screwdriver|Wrench|Pliers|Saw|Drill|Tape Measure|Level|Wheelbarrow|Shovel|Rake|Watering Can|Flowerpot|Hose|Suitcase|Backpack|Wallet|Purse|Basket|Box|Chest|Hanger|Coat Rack|Bookshelf|Desk|Stool|Armchair|Sofa|Cushion|Blanket|Curtain|Rug|Doormat|Vase|Picture Frame|Snow Globe|Hourglass|Alarm Clock|Typewriter|Sewing Machine`),
  nature: words(`Volcano|Rainbow|Mountain|Hill|Valley|Canyon|Cliff|Plateau|Desert|Dune|Oasis|Forest|Jungle|Meadow|Prairie|Wetland|Swamp|Marsh|Tundra|Glacier|Iceberg|Cave Entrance|Waterfall|River|Stream|Lake|Pond|Ocean|Sea|Bay|Lagoon|Coral Reef|Tide Pool|Island|Peninsula|Archipelago|Sandbar|Pebble|Boulder|Crystal|Quartz|Granite|Marble|Limestone|Fossil|Amber|Pearl|Gold|Silver|Copper|Iron|Clay|Sand|Mud|Soil|Moss|Fern|Seaweed|Algae|Lichen|Oak|Pine|Birch|Maple|Willow|Palm|Bamboo|Cactus|Rose|Tulip|Daisy|Sunflower|Lavender|Orchid|Lily|Daffodil|Lotus|Dandelion|Bluebell|Poppy|Ivy|Clover|Acorn|Pine Cone|Leaf|Root|Branch|Bark|Petal|Pollen|Seed|Dew|Frost|Snow|Hail|Rain|Fog|Mist|Cloud|Thunder|Lightning|Breeze|Whirlwind|Monsoon|Aurora|Sunrise|Sunset|Full Moon|Crescent Moon|Eclipse|Comet|Meteor|Asteroid|Galaxy|Constellation|Saturn|Mars|Jupiter|Venus|Milky Way|Black Hole|Nebula|Solar System|North Star|Equator|Geyser|Hot Spring|Icicle|Snowflake`),
  sports: words(`Football|Basketball|Volleyball|Tennis|Badminton|Table Tennis|Squash|Baseball|Softball|Cricket|Rugby|Hockey|Ice Hockey|Golf|Mini Golf|Bowling|Billiards|Darts|Archery|Fencing|Boxing|Wrestling|Judo|Karate|Taekwondo|Gymnastics|Trampoline|Weightlifting|Powerlifting|Running|Sprint|Marathon|Relay Race|Hurdles|High Jump|Long Jump|Pole Vault|Javelin|Discus|Shot Put|Swimming|Diving|Water Polo|Surfing|Windsurfing|Kitesurfing|Sailing|Rowing|Canoeing|Kayaking|Rafting|Skiing|Snowboarding|Ice Skating|Figure Skating|Curling|Bobsleigh|Sledding|Cycling|Mountain Biking|Skateboarding|Roller Skating|Scooter Racing|Climbing|Bouldering|Hiking|Orienteering|Horse Racing|Show Jumping|Polo|Triathlon|Decathlon|Ultimate Frisbee|Disc Golf|Pickleball|Handball|Lacrosse|Netball|Rounders|Tug of War|Dodgeball|Hopscotch|Jump Rope|Capture the Flag|Hide and Seek|Tag|Chess|Checkers|Backgammon|Dominoes|Jigsaw Puzzle|Crossword|Sudoku|Bingo|Charades|Table Football|Air Hockey|Foosball|Kickball|Sepak Takraw`),
  travel: words(`Passport|Boarding Pass|Ticket|Visa|Guidebook|Postcard|Souvenir|Itinerary|Reservation|Check-in|Baggage Claim|Departure Lounge|Duty Free|Security Check|Customs|Window Seat|Aisle Seat|Seat Belt|Overhead Bin|Runway|Control Tower|Jet Bridge|Flight Map|Road Map|Globe|Atlas|GPS|Signpost|Milestone|Traffic Light|Zebra Crossing|Round Trip|Layover|Road Trip|Day Trip|Walking Tour|Cruise|Safari|Backpacking|Camping|Caravan|Motorhome|Tent Peg|Sleeping Bag|Camping Stove|Picnic Basket|Hiking Boot|Trekking Pole|Mosquito Net|Sunscreen|Sunglasses|Sunhat|Life Jacket|Lifebuoy|Anchor|Sail|Oar|Paddle|Steering Wheel|Engine|Propeller|Wing|Helicopter|Airplane|Glider|Hot Air Balloon|Airship|Rocket|Space Shuttle|Submarine|Ferry|Sailboat|Kayak|Canoe|Gondola|Yacht|Tugboat|Cruise Ship|Cargo Ship|Speedboat|Bicycle|Tricycle|Tandem Bicycle|Scooter|Motorcycle|Car|Taxi|Bus|Coach Bus|Tram|Train|Metro|Monorail|Cable Car|Funicular|Tractor|Truck|Ambulance|Fire Engine|Snowmobile|Snowplow|Rickshaw|Horse Carriage|Skateboard|Rollerblades|Ferris Wheel|Chairlift|Escalator|Elevator|Conveyor Belt`),
  fantasy: words(`Pirate|Robot|Dragon|Treasure|Wizard|Witch|Fairy|Elf|Dwarf|Giant|Troll|Goblin|Ogre|Unicorn|Pegasus|Phoenix|Griffin|Mermaid|Centaur|Minotaur|Sphinx|Cyclops|Yeti|Werewolf|Vampire|Ghost|Zombie|Mummy|Skeleton|Genie|Goblin King|Fairy Queen|Knight|Princess|Prince|King|Queen|Jester|Sorcerer|Alchemist|Superhero|Supervillain|Sidekick|Alien|Space Explorer|Time Traveler|Magic Wand|Spellbook|Potion|Crystal Ball|Magic Carpet|Flying Broom|Treasure Map|Treasure Chest|Crown|Tiara|Scepter|Throne|Shield|Sword|Armor|Helmet|Cape|Cloak|Magic Ring|Enchanted Mirror|Portal|Wormhole|Time Machine|Spaceship|Flying Saucer|Invisible Cloak|Dragon Egg|Golden Key|Secret Passage|Trapdoor|Dungeon|Moat|Drawbridge|Tower|Labyrinth|Enchanted Forest|Floating Island|Underwater City|Gingerbread House|Wishing Well|Fountain of Youth|Talking Tree|Seven-league Boots|Magic Bean|Golden Goose|Pumpkin Carriage|Glass Slipper|Poison Apple|Fairy Dust|Magic Lamp|Dragon Cave|Cloud Castle|Crystal Cave|Haunted House`),
  arts: words(`Piano|Guitar|Violin|Cello|Double Bass|Harp|Ukulele|Banjo|Mandolin|Flute|Clarinet|Oboe|Bassoon|Saxophone|Trumpet|Trombone|Tuba|French Horn|Harmonica|Accordion|Bagpipes|Recorder|Drum|Tambourine|Triangle|Xylophone|Marimba|Cymbal|Gong|Bongo|Djembe|Castanets|Maracas|Orchestra|Choir|Duet|Solo|Symphony|Concerto|Sonata|Opera|Ballet|Musical|Jazz|Blues|Rock Music|Pop Music|Folk Music|Lullaby|Anthem|Melody|Harmony|Rhythm|Tempo|Beat|Chorus|Verse|Encore|Rehearsal|Audition|Stage|Curtain Call|Spotlight|Costume|Mask|Puppet|Marionette|Script|Storyboard|Screenplay|Animation|Stop Motion|Sketch|Portrait|Landscape Painting|Still Life|Watercolor|Oil Painting|Charcoal Drawing|Pastel|Collage|Mosaic|Mural|Graffiti|Sculpture|Pottery|Origami|Calligraphy|Embroidery|Knitting|Crochet|Weaving|Patchwork|Quilting|Woodcarving|Glassblowing|Printmaking|Photography|Comic Strip|Graphic Novel|Haiku|Sonnet|Fairy Tale|Fable|Riddle|Limerick|Diary|Travel Journal|Scrapbook|Pop-up Book`),
};

export const IMPOSTER_CATEGORY_LABELS: Record<string, string> = {
  random: 'All topics', animals: 'Animals', food: 'Food & drink', places: 'Places',
  jobs: 'Jobs', movies: 'Movies', objects: 'Everyday objects', nature: 'Nature & space',
  sports: 'Sports & games', travel: 'Travel', fantasy: 'Fantasy', arts: 'Arts & music',
};

export const ALL_IMPOSTER_WORDS = [...new Set(Object.values(IMPOSTER_BANKS).flat())];

export function imposterWords(category = 'random'): string[] {
  return IMPOSTER_BANKS[category] ?? ALL_IMPOSTER_WORDS;
}

